### ISSUE TITLE
React-three/fiber

### ISSUE THREAD

**Issue by m10rten** [akella/DistortedPixels#1]
Hi, first of all: super cool project! i really dig the workings and simplicity.

now here is the thing: i wanted to make this myself, using this repo as inspiration.
i wanted to make it in react/nextjs, and the code is not 1:1 copy-paste, i have been struggling for 2 days now to get it up and running, i have gotten to the point to make the datatexture, to make the shaderMaterial, and to get a loader for the glsl files.
but no results so far.

I was wondering if you could help, or make this repo for react with @react-three/fiber and/or @react-three/drei.

Regards.
@akella

**Comment by akella** [comment]
thank you!
unfortunately i dont have enought resources to rewrite this myself, but r3f community is very good, i think you could ask about the problems there and they will help you in discord!

**Comment by chachaxw** [comment]
@m10rten Hi, I have rewrite with  @react-three/fiber and/or @react-three/drei, please check this repo [chachaxw.github.io](https://github.com/chachaxw/chachaxw.github.io)

**Comment by chachaxw** [comment]
@akella I found a issue with fragment shader code, it' about this line `vec2 newUV = (vUv - vec2(0.5)) * resolution.zw + vec2(0.5);`, if I use `resolution.zw`, my picture can't display normaly, but if I use `resolution.w`, it looks ok. What it means about resolution? or it's just a mistake.
